# Generated by Django 5.2 on 2025-04-16 10:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')], verbose_name='Email')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='Enter a valid Iranian mobile number.')], verbose_name='Mobile Number')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='National ID')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Father Name')),
                ('place_of_issue', models.CharField(blank=True, max_length=100, null=True, verbose_name='Place of Issue')),
            ],
            options={
                'verbose_name': 'Insured Personal Details',
                'verbose_name_plural': 'Insured Personal Details',
            },
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Insurer Name')),
                ('unique_id', models.CharField(max_length=50, unique=True, verbose_name='Insurer Unique ID')),
            ],
            options={
                'verbose_name': 'Insurer',
                'verbose_name_plural': 'Insurers',
            },
        ),
        migrations.CreateModel(
            name='Policyholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Policyholder Name')),
                ('unique_id', models.CharField(max_length=50, unique=True, verbose_name='Policyholder Unique ID')),
            ],
            options={
                'verbose_name': 'Policyholder',
                'verbose_name_plural': 'Policyholders',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('unique_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Policy Unique ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('confirmation_date', models.DateField(blank=True, null=True, verbose_name='Confirmation Date')),
                ('insured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insurances.insured', verbose_name='Insured Person')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurances.insurer', verbose_name='Insurer')),
                ('policyholder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurances.policyholder', verbose_name='Policyholder')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'unique_together': {('insured', 'insurer', 'policyholder', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('unique_id', models.CharField(max_length=50, unique=True, verbose_name='Plan Unique ID')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='insurances.policy', verbose_name='Policy')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='InsuredStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('unique_id', models.CharField(max_length=50, unique=True, verbose_name='Insured Unique ID')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insured_statuses', to='insurances.policy', verbose_name='Policy')),
            ],
            options={
                'verbose_name': 'Insured Status',
                'verbose_name_plural': 'Insured Statuses',
            },
        ),
    ]
